server:
  port: 8002

spring:
  #MySQL参数
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/shortlink?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select 1
      connection-timeout: 20000
      idle-timeout: 300000
      maximum-pool-size: 5
      minimum-idle: 5
  #Redis参数
  data:
    redis:
      host: 127.0.0.1
      port: 6379

# 设置MyBatis的日志实现为SLF4J
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

# 设置日志级别为DEBUG，以便输出SQL语句
logging:
  level:
    org.example.mapper: DEBUG

