server:
  port: 8002

spring:
  application:
      name: admin
  #MySQL参数
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  #Redis参数
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

# 设置MyBatis的日志实现为SLF4J
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

# 设置日志级别为DEBUG，以便输出SQL语句
logging:
  level:
    org.example.mapper: DEBUG

